import 'user_locale_controller.dart';

class UserStrings {
  static const String spotTerm = 'Spot';
  static const String bigEventTerm = 'Big Event';

  static const Map<String, Map<String, String>> _values =
      <String, Map<String, String>>{
    'th': <String, String>{
      'notifications': 'การแจ้งเตือน',
      'no_upcoming_notifications':
          'ไม่มี {spot_term} หรือ {big_event_term} ที่เข้าร่วมไว้ซึ่งกำลังจะเริ่มภายใน 24 ชั่วโมง',
      'account': 'บัญชี',
      'user_info': 'ข้อมูลผู้ใช้',
      'logout': 'ออกจากระบบ',
      'language': 'ภาษา',
      'thai': 'ไทย',
      'english': 'อังกฤษ',
      'chinese': 'จีน',
      'booking': 'การจอง',
      'join_next_challenge_now': 'เข้าร่วมความท้าทายถัดไปตอนนี้',
      'see_more': 'ดูเพิ่มเติม',
      'see_other_big_events': 'ดู Big Event อื่น ๆ',
      'click_book_now': 'คลิกเพื่อจองตอนนี้',
      'you_did_it': 'คุณทำได้แล้ว',
      'total_km': 'กิโลเมตรรวม',
      'total_event_joined': 'จำนวนกิจกรรมที่เข้าร่วมทั้งหมด',
      'unrecorded': 'ยังไม่บันทึก',
      'create_spot': 'สร้าง {spot_term}',
      'spot_joined': '{spot_term} ที่เข้าร่วม',
      'big_event_joined_receipt': '{big_event_term} ที่เข้าร่วมและใบเสร็จ',
      'big_event_starts_at': '{big_event_term} จะเริ่มเวลา {date}',
      'spot_starts_at': '{spot_term} จะเริ่มเวลา {date}',
      'changed_on': 'เปลี่ยนแปลงเมื่อ {date}',
      'data_changed': 'ข้อมูลมีการเปลี่ยนแปลง',
      'select_language': 'เลือกภาษา',
      'spot_detail': 'รายละเอียด {spot_term}',
      'no_data': 'ไม่มีข้อมูล',
      'user_list': 'รายชื่อผู้ใช้',
      'no_users_found_for_spot': 'ไม่พบผู้ใช้สำหรับ {spot_term} นี้',
      'host': 'โฮสต์',
      'user': 'ผู้ใช้',
      'unable_to_load_user_list': 'ไม่สามารถโหลดรายชื่อผู้ใช้ได้: {error}',
      'chat_room_not_available_for_spot': 'ปิดแชทแล้ว',
      'cannot_join_this_spot': 'ไม่สามารถเข้าร่วม {spot_term} นี้ได้',
      'join_failed': 'เข้าร่วมไม่สำเร็จ: {error}',
      'cannot_create_booking_for_spot':
          'ไม่สามารถสร้างการจองสำหรับ {spot_term} นี้ได้',
      'booking_saved_successfully': 'บันทึกการจองเรียบร้อยแล้ว',
      'booking_failed': 'การจองไม่สำเร็จ: {error}',
      'cannot_cancel_booking_for_spot':
          'ไม่สามารถยกเลิกการจองสำหรับ {spot_term} นี้ได้',
      'booking_removed_successfully': 'ยกเลิกการจองเรียบร้อยแล้ว',
      'cancel_booking_failed': 'ยกเลิกการจองไม่สำเร็จ: {error}',
      'cannot_leave_this_spot': 'ไม่สามารถออกจาก {spot_term} นี้ได้',
      'leave_spot': 'ออกจาก {spot_term}',
      'successful': 'สำเร็จ',
      'payment_successful_title': 'ชำระเงินสำเร็จ',
      'payment_successful_subtitle': 'ยืนยันการชำระเงินเรียบร้อยแล้ว',
      'payment_result_title': 'ผลการชำระเงิน',
      'redirecting_to_my_event_in_seconds':
          'กำลังพาไปหน้า My Event ในอีก {seconds} วินาที...',
      'back_to_home': 'กลับหน้าหลัก',
      'leave_failed': 'ออกจาก {spot_term} ไม่สำเร็จ: {error}',
      'cannot_delete_this_spot': 'ไม่สามารถลบ {spot_term} นี้ได้',
      'delete_spot_question': 'ลบ {spot_term} นี้หรือไม่?',
      'delete_spot_for_everyone':
          'การดำเนินการนี้จะลบ {spot_term} นี้สำหรับทุกคน',
      'cancel': 'ยกเลิก',
      'delete': 'ลบ',
      'spot_deleted': 'ลบ {spot_term} แล้ว',
      'delete_failed': 'ลบ {spot_term} ไม่สำเร็จ: {error}',
      'location_not_available': 'ไม่พบข้อมูลตำแหน่ง',
      'edit': 'แก้ไข',
      'role': 'บทบาท',
      'booked': 'จองแล้ว',
      'joined': 'เข้าร่วมแล้ว',
      'open_chat': 'เปิดแชท',
      'event_information': 'ข้อมูลกิจกรรม',
      'guaranteed_items': 'ของที่ได้รับแน่นอน',
      'competition_rewards': 'รางวัลการแข่งขัน',
      'guaranteed_items_subtitle':
          'ของที่คุณจะได้รับจากการเข้าร่วม โดยไม่ต้องแข่งขัน',
      'competition_rewards_subtitle':
          'ของรางวัลที่มีสิทธิ์ได้รับเมื่อแข่งขันตามเงื่อนไขของกิจกรรม',
      'shirt_size': 'ไซซ์เสื้อ',
      'choose_shirt_size': 'เลือกไซซ์เสื้อ',
      'shirt_size_before_checkout':
          'กิจกรรมนี้มีเสื้อวิ่ง กรุณาเลือกไซซ์ก่อนดำเนินการชำระเงิน',
      'shirt_size_required': 'กรุณาเลือกไซซ์เสื้อก่อนดำเนินการ',
      'name_of_event': 'ชื่อกิจกรรม',
      'location': 'สถานที่',
      'location_note': 'หมายเหตุสถานที่',
      'open_in_google_maps': 'เปิดใน Google Maps',
      'date': 'วันที่',
      'time': 'เวลา',
      'description': 'คำอธิบาย',
      'km_per_round': 'กม./รอบ',
      'round': 'รอบ',
      'total_km_caps': 'กม.รวม',
      'how_many_joiner': 'จำนวนผู้เข้าร่วม',
      'booking_reference': 'รหัสการจอง',
      'leave': 'ออก',
      'join': 'เข้าร่วม',
      'runner_profile': 'โปรไฟล์นักวิ่ง',
      'retry': 'ลองอีกครั้ง',
      'profile': 'โปรไฟล์',
      'no_image': 'ไม่มีรูปภาพ',
      'cannot_load_image': 'ไม่สามารถโหลดรูปภาพได้',
      'personal_details': 'ข้อมูลส่วนตัว',
      'document': 'เอกสาร',
      'id_card_image': 'รูปบัตรประชาชน',
      'no_document_image': 'ไม่มีรูปเอกสาร',
      'first_name': 'ชื่อ',
      'last_name': 'นามสกุล',
      'email': 'อีเมล',
      'phone': 'เบอร์โทร',
      'address_details': 'รายละเอียดที่อยู่',
      'full_address': 'ที่อยู่เต็ม',
      'house_no': 'บ้านเลขที่',
      'floor': 'ชั้น',
      'building': 'อาคาร',
      'road': 'ถนน',
      'subdistrict': 'ตำบล',
      'province': 'จังหวัด',
      'district': 'อำเภอ',
      'postal_code': 'รหัสไปรษณีย์',
      'status': 'สถานะ',
      'public_profile': 'โปรไฟล์สาธารณะ',
      'running_summary': 'สรุปการวิ่ง',
      'total_distance': 'ระยะทางรวม',
      'joined_events': 'กิจกรรมที่เข้าร่วม',
      'completed_distance': 'ระยะทางที่วิ่งสำเร็จ',
      'completed_events': 'กิจกรรมที่สำเร็จแล้ว',
      'shared_info': 'ข้อมูลที่เปิดเผย',
      'display_name': 'ชื่อที่แสดง',
      'search': 'ค้นหา',
      'big_event_title': 'Big Event',
      'filters': 'ตัวกรอง',
      'no_big_events_found': 'ไม่พบ Big Event',
      'sync_failed': 'ซิงก์ไม่สำเร็จ: {error}',
      'no_spot_found': 'ไม่พบ Spot',
      'date_with_value': 'วันที่: {value}',
      'time_with_value': 'เวลา: {value}',
      'location_with_value': 'สถานที่: {value}',
      'location_not_specified': 'ยังไม่ระบุสถานที่',
      'code_with_value': 'โค้ด: {value}',
      'lap_with_value': 'รอบละ: {value}',
      'organizer_with_value': 'ผู้จัด: {value}',
      'total_with_value': 'รวม: {value}',
      'people_with_value': 'จำนวนคน: {value}',
      'load_failed': 'โหลดไม่สำเร็จ\n{error}',
      'no_active_user_session': 'ไม่มีเซสชันผู้ใช้ที่ใช้งานอยู่',
      'spot_published_successfully': 'เผยแพร่ Spot เรียบร้อยแล้ว',
      'view_map': 'ดูแผนที่',
      'chat': 'แชท',
      'deleting': 'กำลังลบ...',
      'no_matching_spots': 'ไม่พบ Spot ที่ตรงกัน',
      'no_spots_created_yet': 'ยังไม่มี Spot ที่สร้างไว้',
      'tap_to_create_first_spot': 'แตะ + เพื่อสร้าง Spot แรกของคุณ',
      'no_joined_spots': 'ยังไม่มี Spot ที่เข้าร่วม',
      'left_spot_successfully': 'ออกจาก Spot เรียบร้อยแล้ว',
      'why_are_you_leaving_this_spot': 'คุณต้องการออกจาก Spot นี้เพราะอะไร?',
      'feedback_shared_with_admin': 'ข้อเสนอแนะของคุณจะถูกส่งให้แอดมินตรวจสอบ',
      'please_describe_issue': 'โปรดอธิบายปัญหา',
      'please_describe_safety_concern': 'โปรดอธิบายข้อกังวลด้านความปลอดภัย',
      'please_provide_more_details': 'โปรดให้รายละเอียดเพิ่มเติม',
      'please_enter_at_least_5_characters': 'กรุณากรอกอย่างน้อย 5 ตัวอักษร',
      'confirm_leave': 'ยืนยันการออก',
      'leave_reason_schedule_conflict': 'ติดภารกิจเรื่องเวลา',
      'leave_reason_location_too_far': 'สถานที่ไกลเกินไป',
      'leave_reason_no_longer_interested': 'ไม่สนใจแล้ว',
      'leave_reason_health_injury': 'สุขภาพ / บาดเจ็บ',
      'leave_reason_found_another_activity': 'ไปทำกิจกรรมอื่นแทน',
      'leave_reason_host_problem_participants': 'มีปัญหากับโฮสต์ / ผู้เข้าร่วม',
      'leave_reason_safety_concern': 'กังวลเรื่องความปลอดภัย',
      'other': 'อื่น ๆ',
      'no_completed_joined_events_yet':
          'ยังไม่มี Big Event ที่เข้าร่วมหรือเสร็จสิ้น',
      'paid': 'ชำระแล้ว',
      'available': 'เปิดรับ',
      'completed': 'เสร็จสิ้น',
      'joined_event_detail': 'รายละเอียดกิจกรรมที่เข้าร่วม',
      'organizer': 'ผู้จัด',
      'receipt_payment_information': 'ข้อมูลใบเสร็จ / การชำระเงิน',
      'payment_status': 'สถานะการชำระเงิน',
      'payment_method': 'วิธีชำระเงิน',
      'payment_provider': 'ผู้ให้บริการชำระเงิน',
      'amount_paid': 'จำนวนที่ชำระ',
      'payment_date': 'วันที่ชำระเงิน',
      'payment_reference': 'อ้างอิงการชำระเงิน',
      'receipt_reference': 'อ้างอิงใบเสร็จ',
      'receipt_date': 'วันที่ออกใบเสร็จ',
      'transaction_reference': 'อ้างอิงธุรกรรม',
      'booking_status': 'สถานะการจอง',
      'slip_proof': 'สลิป / หลักฐาน',
      'slip_preview_unavailable': 'ไม่สามารถแสดงตัวอย่างสลิปได้',
      'open_slip': 'เปิดสลิป',
      'open_receipt': 'เปิดใบเสร็จ',
      'no_receipt_details_available':
          'ไม่มีรายละเอียดใบเสร็จสำหรับกิจกรรมที่เข้าร่วมนี้',
      'resolving_location': 'กำลังค้นหาสถานที่...',
      'could_not_open_link': 'ไม่สามารถเปิดลิงก์ได้',
      'spot_booking': 'การจอง Spot',
      'booked_spots_waiting_join': 'Spot ที่จองไว้และกำลังรอเข้าร่วม',
      'no_pending_spot_bookings_yet': 'ยังไม่มีการจอง Spot ที่รออยู่',
      'big_event_favorite': 'Big Event ที่ถูกใจ',
      'saved_big_events_unpaid': 'Big Event ที่บันทึกไว้และยังไม่ได้ชำระ',
      'no_favorite_big_events_yet': 'ยังไม่มี Big Event ที่ถูกใจ',
      'removed_from_favorites': 'นำออกจากรายการโปรดแล้ว',
      'remove_favorite': 'นำออกจากรายการโปรด',
      'price_with_value': 'ราคา: {value}',
      'ref_with_value': 'อ้างอิง: {value}',
      'distance_overview': 'ภาพรวมระยะทาง',
      'distance_overview_subtitle': 'สมาชิกทั้งหมดถูกจัดกลุ่มตามระยะห่างของคุณ',
      'comparison_ahead_far_title': 'คุณนำมากกว่า 10 กม.',
      'comparison_ahead_near_title': 'คุณนำน้อยกว่า 10 กม.',
      'comparison_behind_near_title': 'คุณกำลังจะแซงในระยะ 1-10 กม.',
      'comparison_behind_far_title': 'คุณยังห่างมากกว่า 10 กม.',
      'comparison_tied_title': 'ระยะทางเท่ากัน',
      'comparison_ahead_far_subtitle': 'สมาชิกที่คุณนำอยู่แบบสบาย ๆ',
      'comparison_ahead_near_subtitle': 'สมาชิกที่คุณนำอยู่ไม่เกิน 10 กม.',
      'comparison_behind_near_subtitle': 'สมาชิกที่คุณมีโอกาสแซงได้เร็ว ๆ นี้',
      'comparison_behind_far_subtitle': 'สมาชิกที่ยังนำหน้าคุณมากกว่า 10 กม.',
      'comparison_tied_subtitle': 'สมาชิกที่มีระยะทางรวมเท่ากับคุณ',
      'no_comparable_members_found': 'ไม่พบสมาชิกที่นำมาเปรียบเทียบได้',
      'gap_with_value': 'ระยะห่าง: {value}',
      'close': 'ปิด',
      'this_runner': 'นักวิ่งคนนี้',
      'compare_popup_done_self': 'คุณทำได้แล้ว',
      'compare_popup_done_other': '{name} ทำได้แล้ว',
      'compare_popup_close_to':
          'คุณใกล้ตาม {name} ทันแล้ว เหลืออีกเพียง {distance}',
      'compare_popup_behind': 'คุณตามหลัง {name} อยู่ {distance}',
      'compare_popup_ahead_far': 'คุณนำ {name} อยู่ {distance} สุดยอดมาก',
      'compare_popup_ahead_near':
          'คุณนำ {name} อยู่ {distance} รักษาจังหวะนี้ไว้',
      'compare_member_equal': '{name} มีระยะทางเท่ากับคุณ',
      'compare_member_other_ahead': '{name} นำคุณอยู่ {distance}',
      'compare_member_you_ahead': 'คุณนำ {name} อยู่ {distance}',
      'compare_profile_equal': 'คุณมีระยะทางเท่ากัน',
      'compare_profile_behind': 'พยายามอีกนิด อีก {distance} จะตามทัน',
      'compare_profile_ahead': 'คุณนำอยู่ {distance}',
      'member_completed_summary':
          'สมาชิกคนนี้วิ่งสำเร็จ {distance} และสำเร็จ {count} กิจกรรม',
    },
    'en': <String, String>{
      'notifications': 'Notifications',
      'no_upcoming_notifications':
          'No joined {spot_term} or {big_event_term} is starting within 24 hours.',
      'account': 'Account',
      'user_info': 'User Info',
      'logout': 'Logout',
      'language': 'Language',
      'thai': 'Thai',
      'english': 'English',
      'chinese': 'Chinese',
      'booking': 'Booking',
      'join_next_challenge_now': 'Join the next challenge now',
      'see_more': 'See more',
      'see_other_big_events': 'See Other Big Events',
      'click_book_now': 'Click to book now',
      'you_did_it': 'You did it.',
      'total_km': 'Total km.',
      'total_event_joined': 'Total number of events joined',
      'unrecorded': 'Unrecorded',
      'create_spot': 'Create {spot_term}',
      'spot_joined': '{spot_term} Joined',
      'big_event_joined_receipt': '{big_event_term} Joined & Receipt',
      'big_event_starts_at': '{big_event_term} starts at {date}',
      'spot_starts_at': '{spot_term} starts at {date}',
      'changed_on': 'Changed on {date}',
      'data_changed': 'Data changed',
      'select_language': 'Select language',
      'spot_detail': '{spot_term} Detail',
      'no_data': 'No data',
      'user_list': 'User List',
      'no_users_found_for_spot': 'No users found for this {spot_term}.',
      'host': 'Host',
      'user': 'User',
      'unable_to_load_user_list': 'Unable to load user list: {error}',
      'chat_room_not_available_for_spot': 'Chat closed.',
      'cannot_join_this_spot': 'Cannot join this {spot_term}.',
      'join_failed': 'Join failed: {error}',
      'cannot_create_booking_for_spot':
          'Cannot create booking for this {spot_term}.',
      'booking_saved_successfully': 'Booking saved successfully',
      'booking_failed': 'Booking failed: {error}',
      'cannot_cancel_booking_for_spot':
          'Cannot cancel booking for this {spot_term}.',
      'booking_removed_successfully': 'Booking removed successfully',
      'cancel_booking_failed': 'Cancel booking failed: {error}',
      'cannot_leave_this_spot': 'Cannot leave this {spot_term}.',
      'leave_spot': 'Leave {spot_term}',
      'successful': 'successful',
      'payment_successful_title': 'Payment Successful',
      'payment_successful_subtitle':
          'Your payment has been confirmed successfully.',
      'payment_result_title': 'Payment Result',
      'redirecting_to_my_event_in_seconds':
          'Redirecting to My Event in {seconds} seconds...',
      'back_to_home': 'Back to Home',
      'leave_failed': 'Leave failed: {error}',
      'cannot_delete_this_spot': 'Cannot delete this {spot_term}.',
      'delete_spot_question': 'Delete {spot_term}?',
      'delete_spot_for_everyone':
          'This will delete the {spot_term} for everyone.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'spot_deleted': '{spot_term} deleted',
      'delete_failed': 'Delete failed: {error}',
      'location_not_available': 'Location is not available.',
      'edit': 'Edit',
      'role': 'Role',
      'booked': 'Booked',
      'joined': 'Joined',
      'open_chat': 'Open Chat',
      'event_information': 'Event Information',
      'guaranteed_items': 'Guaranteed Items',
      'competition_rewards': 'Competition Rewards',
      'guaranteed_items_subtitle':
          'Items you receive from joining without needing to compete.',
      'competition_rewards_subtitle':
          'Prizes you can earn when competing under the event rules.',
      'shirt_size': 'Shirt Size',
      'choose_shirt_size': 'Choose shirt size',
      'shirt_size_before_checkout':
          'This event includes a running shirt. Please choose your size before checkout.',
      'shirt_size_required': 'Please choose a shirt size before continuing.',
      'name_of_event': 'Name of event',
      'location': 'Location',
      'location_note': 'Location Note',
      'open_in_google_maps': 'Open in Google Maps',
      'date': 'Date',
      'time': 'Time',
      'description': 'Description',
      'km_per_round': 'KM/Round',
      'round': 'Round',
      'total_km_caps': 'Total KM',
      'how_many_joiner': 'How many joiner?',
      'booking_reference': 'Booking Reference',
      'leave': 'Leave',
      'join': 'Join',
      'runner_profile': 'Runner Profile',
      'retry': 'Retry',
      'profile': 'Profile',
      'no_image': 'No image',
      'cannot_load_image': 'Cannot load image',
      'personal_details': 'Personal Details',
      'document': 'Document',
      'id_card_image': 'ID Card Image',
      'no_document_image': 'No document image',
      'first_name': 'First name',
      'last_name': 'Last name',
      'email': 'Email',
      'phone': 'Phone',
      'address_details': 'Address Details',
      'full_address': 'Full Address',
      'house_no': 'House No.',
      'floor': 'Floor',
      'building': 'Building',
      'road': 'Road',
      'subdistrict': 'Subdistrict',
      'province': 'Province',
      'district': 'District',
      'postal_code': 'Postal Code',
      'status': 'Status',
      'public_profile': 'Public Profile',
      'running_summary': 'Running Summary',
      'total_distance': 'Total distance',
      'joined_events': 'Joined events',
      'completed_distance': 'Completed distance',
      'completed_events': 'Completed events',
      'shared_info': 'Shared Info',
      'display_name': 'Display name',
      'search': 'Search',
      'big_event_title': 'Big Event',
      'filters': 'Filters',
      'no_big_events_found': 'No big events found',
      'sync_failed': 'Sync failed: {error}',
      'no_spot_found': 'No {spot_term} found',
      'date_with_value': 'Date: {value}',
      'time_with_value': 'Time: {value}',
      'location_with_value': 'Location: {value}',
      'location_not_specified': 'Location not specified',
      'code_with_value': 'Code: {value}',
      'lap_with_value': 'Lap: {value}',
      'organizer_with_value': 'Organizer: {value}',
      'total_with_value': 'Total: {value}',
      'people_with_value': 'People: {value}',
      'load_failed': 'Load failed\n{error}',
      'no_active_user_session': 'No active user session',
      'spot_published_successfully': '{spot_term} published successfully',
      'view_map': 'View Map',
      'chat': 'Chat',
      'deleting': 'Deleting...',
      'no_matching_spots': 'No matching {spot_termLower}s',
      'no_spots_created_yet': 'No {spot_termLower}s created yet',
      'tap_to_create_first_spot':
          'Tap + to create your first {spot_termLower}.',
      'no_joined_spots': 'No joined {spot_termLower}s',
      'left_spot_successfully': 'Left {spot_termLower} successfully',
      'why_are_you_leaving_this_spot':
          'Why are you leaving this {spot_termLower}?',
      'feedback_shared_with_admin':
          'Your feedback will be shared with admin for review.',
      'please_describe_issue': 'Please describe the issue',
      'please_describe_safety_concern': 'Please describe the safety concern',
      'please_provide_more_details': 'Please provide more details',
      'please_enter_at_least_5_characters':
          'Please enter at least 5 characters',
      'confirm_leave': 'Confirm Leave',
      'leave_reason_schedule_conflict': 'Schedule conflict',
      'leave_reason_location_too_far': 'Location too far',
      'leave_reason_no_longer_interested': 'No longer interested',
      'leave_reason_health_injury': 'Health / injury',
      'leave_reason_found_another_activity': 'Found another activity',
      'leave_reason_host_problem_participants':
          'Host/problem with participants',
      'leave_reason_safety_concern': 'Safety concern',
      'other': 'Other',
      'no_completed_joined_events_yet': 'No completed joined events yet',
      'paid': 'PAID',
      'available': 'Available',
      'completed': 'COMPLETED',
      'joined_event_detail': 'Joined Event Detail',
      'organizer': 'Organizer',
      'receipt_payment_information': 'Receipt / Payment Information',
      'payment_status': 'Payment status',
      'payment_method': 'Payment method',
      'payment_provider': 'Payment provider',
      'amount_paid': 'Amount paid',
      'payment_date': 'Payment date',
      'payment_reference': 'Payment reference',
      'receipt_reference': 'Receipt reference',
      'receipt_date': 'Receipt date',
      'transaction_reference': 'Transaction reference',
      'booking_status': 'Booking status',
      'slip_proof': 'Slip / Proof',
      'slip_preview_unavailable': 'Slip preview unavailable',
      'open_slip': 'Open Slip',
      'open_receipt': 'Open Receipt',
      'no_receipt_details_available':
          'No receipt details are available for this joined event.',
      'resolving_location': 'Resolving location...',
      'could_not_open_link': 'Could not open link',
      'spot_booking': '{spot_term} Booking',
      'booked_spots_waiting_join':
          'Booked {spot_termLower}s that are still waiting for Join',
      'no_pending_spot_bookings_yet':
          'No pending {spot_termLower} bookings yet',
      'big_event_favorite': '{big_event_term} Favorite',
      'saved_big_events_unpaid':
          'Saved big events that you have not paid for yet',
      'no_favorite_big_events_yet': 'No favorite big events yet',
      'removed_from_favorites': 'Removed from favorites',
      'remove_favorite': 'Remove favorite',
      'price_with_value': 'Price: {value}',
      'ref_with_value': 'Ref: {value}',
      'distance_overview': 'Distance Overview',
      'distance_overview_subtitle': 'All members grouped by your distance gap.',
      'comparison_ahead_far_title': 'You lead by more than 10 km',
      'comparison_ahead_near_title': 'You lead by 0-9 km',
      'comparison_behind_near_title': 'You are about to overtake (1-10 km)',
      'comparison_behind_far_title': 'You are more than 10 km behind',
      'comparison_tied_title': 'Equal distance',
      'comparison_ahead_far_subtitle': 'Members you are leading comfortably.',
      'comparison_ahead_near_subtitle':
          'Members you are leading by less than 10 km.',
      'comparison_behind_near_subtitle': 'Members you can catch soon.',
      'comparison_behind_far_subtitle': 'Members still far ahead of you.',
      'comparison_tied_subtitle':
          'Members with the same total distance as you.',
      'no_comparable_members_found': 'No comparable members found.',
      'gap_with_value': 'Gap: {value}',
      'close': 'Close',
      'this_runner': 'this runner',
      'compare_popup_done_self': 'You did it already.',
      'compare_popup_done_other': '{name}, you did it already.',
      'compare_popup_close_to':
          'You are close to {name} — only {distance} away. Push a little more!!!',
      'compare_popup_behind':
          'You are behind {name} by {distance}. Keep going — never give up!',
      'compare_popup_ahead_far':
          'You are ahead of {name} by {distance}. You are awesome!',
      'compare_popup_ahead_near':
          'You are ahead of {name} by {distance}. Keep it up!',
      'compare_member_equal': '{name} is equal to you.',
      'compare_member_other_ahead': '{name} is ahead of you by {distance}.',
      'compare_member_you_ahead': 'You are ahead of {name} by {distance}.',
      'compare_profile_equal': 'You are equal.',
      'compare_profile_behind': 'Push harder — {distance} to catch up.',
      'compare_profile_ahead': 'You are ahead by {distance}.',
      'member_completed_summary':
          'This member has completed {distance} and {count} activities.',
    },
    'zh': <String, String>{
      'notifications': '通知',
      'no_upcoming_notifications':
          '未来24小时内没有已参加的 {spot_term} 或 {big_event_term} 即将开始。',
      'account': '账户',
      'user_info': '用户信息',
      'logout': '退出登录',
      'language': '语言',
      'thai': '泰语',
      'english': '英语',
      'chinese': '中文',
      'booking': '收藏与预订',
      'join_next_challenge_now': '立即加入下一个挑战',
      'see_more': '查看更多',
      'see_other_big_events': '查看更多 Big Event',
      'click_book_now': '点击立即预订',
      'you_did_it': '你做到了。',
      'total_km': '总公里数',
      'total_event_joined': '已参加活动总数',
      'unrecorded': '未记录',
      'create_spot': '创建 {spot_term}',
      'spot_joined': '已加入的 {spot_term}',
      'big_event_joined_receipt': '已参加 {big_event_term} 与收据',
      'big_event_starts_at': '{big_event_term} 将于 {date} 开始',
      'spot_starts_at': '{spot_term} 将于 {date} 开始',
      'changed_on': '变更于 {date}',
      'data_changed': '数据已更改',
      'select_language': '选择语言',
      'spot_detail': '{spot_term} 详情',
      'no_data': '暂无数据',
      'user_list': '用户列表',
      'no_users_found_for_spot': '此 {spot_term} 暂无用户。',
      'host': '房主',
      'user': '用户',
      'unable_to_load_user_list': '无法加载用户列表：{error}',
      'chat_room_not_available_for_spot': '聊天已关闭。',
      'cannot_join_this_spot': '无法加入此 {spot_term}。',
      'join_failed': '加入失败：{error}',
      'cannot_create_booking_for_spot': '无法为此 {spot_term} 创建预订。',
      'booking_saved_successfully': '预订已保存',
      'booking_failed': '预订失败：{error}',
      'cannot_cancel_booking_for_spot': '无法取消此 {spot_term} 的预订。',
      'booking_removed_successfully': '预订已取消',
      'cancel_booking_failed': '取消预订失败：{error}',
      'cannot_leave_this_spot': '无法退出此 {spot_term}。',
      'leave_spot': '退出 {spot_term}',
      'successful': '成功',
      'payment_successful_title': '支付成功',
      'payment_successful_subtitle': '你的付款已成功确认。',
      'payment_result_title': '支付结果',
      'redirecting_to_my_event_in_seconds': '将在 {seconds} 秒后跳转到 My Event 页面...',
      'back_to_home': '返回首页',
      'leave_failed': '退出失败：{error}',
      'cannot_delete_this_spot': '无法删除此 {spot_term}。',
      'delete_spot_question': '删除 {spot_term}？',
      'delete_spot_for_everyone': '此操作会为所有人删除这个 {spot_term}。',
      'cancel': '取消',
      'delete': '删除',
      'spot_deleted': '{spot_term} 已删除',
      'delete_failed': '删除失败：{error}',
      'location_not_available': '位置不可用。',
      'edit': '编辑',
      'role': '角色',
      'booked': '已预订',
      'joined': '已加入',
      'open_chat': '打开聊天',
      'event_information': '活动信息',
      'guaranteed_items': '必得物品',
      'competition_rewards': '竞赛奖励',
      'guaranteed_items_subtitle': '参加活动即可获得的物品，无需比赛。',
      'competition_rewards_subtitle': '按照活动规则参与比赛后可获得的奖励。',
      'shirt_size': '衣服尺码',
      'choose_shirt_size': '选择衣服尺码',
      'shirt_size_before_checkout':
          '此活动包含跑步衣，请在结账前选择尺码。',
      'shirt_size_required': '请先选择衣服尺码。',
      'name_of_event': '活动名称',
      'location': '地点',
      'location_note': '地点备注',
      'open_in_google_maps': '在 Google 地图中打开',
      'date': '日期',
      'time': '时间',
      'description': '说明',
      'km_per_round': '每圈公里数',
      'round': '圈数',
      'total_km_caps': '总公里数',
      'how_many_joiner': '参与人数',
      'booking_reference': '预订编号',
      'leave': '退出',
      'join': '加入',
      'runner_profile': '跑者资料',
      'retry': '重试',
      'profile': '个人资料',
      'no_image': '没有图片',
      'cannot_load_image': '无法加载图片',
      'personal_details': '个人信息',
      'document': '证件',
      'id_card_image': '身份证图片',
      'no_document_image': '没有证件图片',
      'first_name': '名字',
      'last_name': '姓氏',
      'email': '电子邮箱',
      'phone': '电话',
      'address_details': '地址详情',
      'full_address': '完整地址',
      'house_no': '门牌号',
      'floor': '楼层',
      'building': '建筑物',
      'road': '道路',
      'subdistrict': '分区',
      'province': '省',
      'district': '区',
      'postal_code': '邮政编码',
      'status': '状态',
      'public_profile': '公开资料',
      'running_summary': '跑步摘要',
      'total_distance': '总距离',
      'joined_events': '已参加活动',
      'completed_distance': '已完成距离',
      'completed_events': '已完成活动',
      'shared_info': '公开信息',
      'display_name': '显示名称',
      'search': '搜索',
      'big_event_title': 'Big Event',
      'filters': '筛选',
      'no_big_events_found': '未找到 Big Event',
      'sync_failed': '同步失败：{error}',
      'no_spot_found': '未找到 {spot_term}',
      'date_with_value': '日期: {value}',
      'time_with_value': '时间: {value}',
      'location_with_value': '地点: {value}',
      'location_not_specified': '未指定地点',
      'code_with_value': '代码: {value}',
      'lap_with_value': '每圈: {value}',
      'organizer_with_value': '主办方: {value}',
      'total_with_value': '总计: {value}',
      'people_with_value': '人数: {value}',
      'load_failed': '加载失败\n{error}',
      'no_active_user_session': '没有有效的用户会话',
      'spot_published_successfully': '{spot_term} 发布成功',
      'view_map': '查看地图',
      'chat': '聊天',
      'deleting': '删除中...',
      'no_matching_spots': '没有匹配的 {spot_term}',
      'no_spots_created_yet': '还没有创建 {spot_term}',
      'tap_to_create_first_spot': '点击 + 创建你的第一个 {spot_term}',
      'no_joined_spots': '还没有已加入的 {spot_term}',
      'left_spot_successfully': '已成功退出 {spot_term}',
      'why_are_you_leaving_this_spot': '你为什么要退出这个 {spot_term}？',
      'feedback_shared_with_admin': '你的反馈将发送给管理员审核。',
      'please_describe_issue': '请描述问题',
      'please_describe_safety_concern': '请描述安全方面的担忧',
      'please_provide_more_details': '请提供更多详细信息',
      'please_enter_at_least_5_characters': '请至少输入 5 个字符',
      'confirm_leave': '确认退出',
      'leave_reason_schedule_conflict': '时间冲突',
      'leave_reason_location_too_far': '地点太远',
      'leave_reason_no_longer_interested': '不再感兴趣',
      'leave_reason_health_injury': '健康 / 受伤',
      'leave_reason_found_another_activity': '找到其他活动',
      'leave_reason_host_problem_participants': '与主办方 / 参与者有问题',
      'leave_reason_safety_concern': '安全顾虑',
      'other': '其他',
      'no_completed_joined_events_yet': '还没有已参加并完成的活动',
      'paid': '已支付',
      'available': '可加入',
      'completed': '已完成',
      'joined_event_detail': '已参加活动详情',
      'organizer': '主办方',
      'receipt_payment_information': '收据 / 支付信息',
      'payment_status': '支付状态',
      'payment_method': '支付方式',
      'payment_provider': '支付服务商',
      'amount_paid': '支付金额',
      'payment_date': '支付日期',
      'payment_reference': '支付参考号',
      'receipt_reference': '收据参考号',
      'receipt_date': '收据日期',
      'transaction_reference': '交易参考号',
      'booking_status': '预订状态',
      'slip_proof': '凭证 / 证明',
      'slip_preview_unavailable': '无法预览凭证',
      'open_slip': '打开凭证',
      'open_receipt': '打开收据',
      'no_receipt_details_available': '此已参加活动暂无收据详情',
      'resolving_location': '正在解析地点...',
      'could_not_open_link': '无法打开链接',
      'spot_booking': '{spot_term} 预订',
      'booked_spots_waiting_join': '已预订并仍在等待加入的 {spot_term}',
      'no_pending_spot_bookings_yet': '还没有待加入的 {spot_term} 预订',
      'big_event_favorite': '{big_event_term} 收藏',
      'saved_big_events_unpaid': '已保存但尚未支付的 Big Event',
      'no_favorite_big_events_yet': '还没有收藏的 Big Event',
      'removed_from_favorites': '已从收藏中移除',
      'remove_favorite': '移除收藏',
      'price_with_value': '价格: {value}',
      'ref_with_value': '参考号: {value}',
      'distance_overview': '距离总览',
      'distance_overview_subtitle': '所有成员会按与你的距离差分组显示',
      'comparison_ahead_far_title': '你领先超过 10 公里',
      'comparison_ahead_near_title': '你领先少于 10 公里',
      'comparison_behind_near_title': '你即将反超（1-10 公里）',
      'comparison_behind_far_title': '你仍落后超过 10 公里',
      'comparison_tied_title': '距离相同',
      'comparison_ahead_far_subtitle': '这些成员目前被你明显领先',
      'comparison_ahead_near_subtitle': '这些成员目前被你领先不到 10 公里',
      'comparison_behind_near_subtitle': '这些成员你很快就能追上',
      'comparison_behind_far_subtitle': '这些成员目前仍领先你超过 10 公里',
      'comparison_tied_subtitle': '这些成员与你的总距离相同',
      'no_comparable_members_found': '没有可比较的成员',
      'gap_with_value': '差距: {value}',
      'close': '关闭',
      'this_runner': '这位跑者',
      'compare_popup_done_self': '你已经做到了',
      'compare_popup_done_other': '{name} 已经做到了',
      'compare_popup_close_to': '你快追上 {name} 了，只差 {distance}',
      'compare_popup_behind': '你落后 {name} {distance}',
      'compare_popup_ahead_far': '你领先 {name} {distance}，非常棒',
      'compare_popup_ahead_near': '你领先 {name} {distance}，继续保持',
      'compare_member_equal': '{name} 与你距离相同',
      'compare_member_other_ahead': '{name} 领先你 {distance}',
      'compare_member_you_ahead': '你领先 {name} {distance}',
      'compare_profile_equal': '你们距离相同',
      'compare_profile_behind': '再努力一点，还差 {distance} 就能追上',
      'compare_profile_ahead': '你领先 {distance}',
      'member_completed_summary': '这位成员已完成 {distance}，并完成了 {count} 个活动',
    },
  };

  static const Map<String, Map<String, String>> _extraValues =
      <String, Map<String, String>>{
    'th': <String, String>{
      'google_maps_web_not_configured':
          'Google Maps ยังไม่ถูกตั้งค่าสำหรับเว็บ ให้เพิ่ม Maps JavaScript API script ใน web/index.html',
      'distance_per_lap': 'ระยะ/รอบ',
      'number_of_laps': 'จำนวนรอบ',
      'fee': 'ค่าสมัคร',
      'meeting_point_not_provided': 'ยังไม่มีข้อมูลจุดนัดพบ',
      'meeting_point_with_value': 'จุดนัดพบ: {value}',
      'open_map_failed': 'เปิดแผนที่ไม่สำเร็จ: {error}',
      'please_log_in_again': 'กรุณาเข้าสู่ระบบใหม่',
      'checkout_title': 'ชำระเงิน',
      'automatic_online_payment': 'ชำระเงินออนไลน์อัตโนมัติ',
      'stripe_promptpay_auto_subtitle':
          'PromptPay ใช้ Stripe และระบบจะติดตามสถานะการชำระเงินให้อัตโนมัติ',
      'start_stripe_payment': 'เริ่มชำระเงินผ่าน Stripe',
      'stripe_payment_in_progress': 'กำลังดำเนินการชำระเงินผ่าน Stripe',
      'promptpay_with_value': 'PromptPay: {value}',
      'payment_mode_with_value': 'โหมดการชำระเงิน: {value}',
      'payment_id_with_value': 'Payment ID: {value}',
      'booking_id_with_value': 'Booking ID: {value}',
      'back_to_event': 'กลับไปหน้ากิจกรรม',
      'back_to_big_events': 'กลับไปหน้า Big Event',
      'payment_context_incomplete':
          'ข้อมูลการชำระเงินไม่ครบ กรุณากลับไปที่กิจกรรมแล้วลองใหม่อีกครั้ง',
      'required_payment_context_missing':
          'ข้อมูลที่จำเป็นสำหรับการชำระเงินในรอบนี้ไม่ครบ',
      'no_payment_methods_available':
          'ขณะนี้กิจกรรมนี้ยังไม่มีช่องทางชำระเงินที่ใช้งานได้',
      'manual_payment_not_fully_configured':
          'การชำระเงินแบบ manual สำหรับกิจกรรมนี้ยังตั้งค่าไม่ครบ',
    },
    'en': <String, String>{
      'google_maps_web_not_configured':
          'Google Maps is not configured for web. Add the Maps JavaScript API script in web/index.html.',
      'distance_per_lap': 'Distance/lap',
      'number_of_laps': 'Number of laps',
      'fee': 'Fee',
      'meeting_point_not_provided': 'Meeting point not provided',
      'meeting_point_with_value': 'Meeting point: {value}',
      'open_map_failed': 'Open map failed: {error}',
      'please_log_in_again': 'Please log in again.',
      'checkout_title': 'Checkout',
      'automatic_online_payment': 'Automatic Online Payment',
      'stripe_promptpay_auto_subtitle':
          'PromptPay uses Stripe. Backend payment status is tracked automatically.',
      'start_stripe_payment': 'Start Stripe Payment',
      'stripe_payment_in_progress': 'Stripe Payment In Progress',
      'promptpay_with_value': 'PromptPay: {value}',
      'payment_mode_with_value': 'Payment mode: {value}',
      'payment_id_with_value': 'Payment ID: {value}',
      'booking_id_with_value': 'Booking ID: {value}',
      'back_to_event': 'Back to Event',
      'back_to_big_events': 'Back to Big Events',
      'payment_context_incomplete':
          'Payment information is incomplete. Please return to the event and try again.',
      'required_payment_context_missing':
          'Required payment context is missing for this checkout session.',
      'no_payment_methods_available':
          'No payment methods are currently available for this event.',
      'manual_payment_not_fully_configured':
          'Manual payment is not fully configured for this event.',
    },
    'zh': <String, String>{
      'google_maps_web_not_configured':
          'Google Maps 尚未为网页端完成配置，请在 web/index.html 中加入 Maps JavaScript API script。',
      'distance_per_lap': '每圈距离',
      'number_of_laps': '圈数',
      'fee': '费用',
      'meeting_point_not_provided': '未提供会合点',
      'meeting_point_with_value': '会合点: {value}',
      'open_map_failed': '打开地图失败：{error}',
      'please_log_in_again': '请重新登录。',
      'checkout_title': '结账',
      'automatic_online_payment': '自动在线支付',
      'stripe_promptpay_auto_subtitle': 'PromptPay 使用 Stripe，系统会自动追踪付款状态。',
      'start_stripe_payment': '开始通过 Stripe 支付',
      'stripe_payment_in_progress': 'Stripe 支付进行中',
      'promptpay_with_value': 'PromptPay: {value}',
      'payment_mode_with_value': '支付模式: {value}',
      'payment_id_with_value': 'Payment ID: {value}',
      'booking_id_with_value': 'Booking ID: {value}',
      'back_to_event': '返回活动页面',
      'back_to_big_events': '返回 Big Event 页面',
      'payment_context_incomplete': '支付信息不完整，请返回活动页面后重试。',
      'required_payment_context_missing': '本次结账缺少必要的支付上下文信息。',
      'no_payment_methods_available': '当前此活动暂无可用支付方式。',
      'manual_payment_not_fully_configured': '此活动的手动支付配置尚未完成。',
    },
  };

  static const Map<String, Map<String, String>> _spotFormExtraValues =
      <String, Map<String, String>>{
    'th': <String, String>{
      'create_your_spot': 'สร้าง Spot ของคุณ',
      'edit_spot': 'แก้ไข Spot',
      'spot_image': 'รูปภาพ Spot',
      'upload_spot_cover': 'อัปโหลดภาพปก Spot',
      'upload_cover': 'อัปโหลดภาพปก',
      'choose_one_image_for_your_activity':
          'เลือกรูปภาพหนึ่งรูปสำหรับกิจกรรมของคุณ',
      'change': 'เปลี่ยน',
      'basic_information': 'ข้อมูลพื้นฐาน',
      'spot_name': 'ชื่อ Spot',
      'spot_name_hint': 'วิ่งเช้าที่สวนสาธารณะ',
      'select_date': 'เลือกวันที่',
      'select_time': 'เลือกเวลา',
      'pick_location_on_map': 'ปักหมุดสถานที่บนแผนที่',
      'location_note_hint': 'ใกล้ประตู 2 หน้าคาเฟ่',
      'activity_details': 'รายละเอียดกิจกรรม',
      'description_hint': 'บอกผู้เข้าร่วมว่ากิจกรรมนี้เกี่ยวกับอะไร',
      'max_participants': 'จำนวนผู้เข้าร่วมสูงสุด',
      'spot_is_free_no_payment_required': 'Spot เป็นกิจกรรมฟรี ไม่ต้องชำระเงิน',
      'save_changes': 'บันทึกการเปลี่ยนแปลง',
      'publish': 'เผยแพร่',
      'picked_location': 'ตำแหน่งที่เลือก',
      'required_field': 'จำเป็นต้องกรอก',
      'auto_calculated_from_km_and_round':
          'คำนวณอัตโนมัติจากกม./รอบ และจำนวนรอบ',
      'selected_image_too_large':
          'รูปภาพที่เลือกมีขนาดใหญ่เกินไป กรุณาเลือกรูปที่เล็กลง',
      'please_pick_location_on_map': 'กรุณาเลือกตำแหน่งบนแผนที่',
      'please_select_date': 'กรุณาเลือกวันที่',
      'please_select_time': 'กรุณาเลือกเวลา',
      'save_failed': 'บันทึกไม่สำเร็จ: {error}',
      'publish_failed': 'เผยแพร่ไม่สำเร็จ: {error}',
    },
    'en': <String, String>{
      'create_your_spot': 'Create your Spot',
      'edit_spot': 'Edit Spot',
      'spot_image': 'Spot image',
      'upload_spot_cover': 'Upload Spot Cover',
      'upload_cover': 'Upload Cover',
      'choose_one_image_for_your_activity':
          'Choose one image for your activity',
      'change': 'Change',
      'basic_information': 'Basic information',
      'spot_name': 'Spot name',
      'spot_name_hint': 'Morning Run at the Park',
      'select_date': 'Select date',
      'select_time': 'Select time',
      'pick_location_on_map': 'Pick location on map',
      'location_note_hint': 'Near gate 2, in front of the cafe',
      'activity_details': 'Activity details',
      'description_hint': 'Tell people what the activity is about',
      'max_participants': 'Max participants',
      'spot_is_free_no_payment_required':
          'Spot is a free activity. No payment is required.',
      'save_changes': 'Save Changes',
      'publish': 'Publish',
      'picked_location': 'Picked location',
      'required_field': 'Required',
      'auto_calculated_from_km_and_round':
          'Auto-calculated from KM/Round and Round',
      'selected_image_too_large':
          'Selected image is too large. Please choose a smaller image.',
      'please_pick_location_on_map': 'Please pick location on map',
      'please_select_date': 'Please select date',
      'please_select_time': 'Please select time',
      'save_failed': 'Save failed: {error}',
      'publish_failed': 'Publish failed: {error}',
    },
    'zh': <String, String>{
      'create_your_spot': '创建你的 Spot',
      'edit_spot': '编辑 Spot',
      'spot_image': 'Spot 图片',
      'upload_spot_cover': '上传 Spot 封面',
      'upload_cover': '上传封面',
      'choose_one_image_for_your_activity': '为你的活动选择一张图片',
      'change': '更改',
      'basic_information': '基本信息',
      'spot_name': 'Spot 名称',
      'spot_name_hint': '公园晨跑',
      'select_date': '选择日期',
      'select_time': '选择时间',
      'pick_location_on_map': '在地图上选择地点',
      'location_note_hint': '靠近 2 号门，在咖啡馆前面',
      'activity_details': '活动详情',
      'description_hint': '告诉大家这个活动的内容',
      'max_participants': '最多参与人数',
      'spot_is_free_no_payment_required': 'Spot 是免费活动，无需付款。',
      'save_changes': '保存更改',
      'publish': '发布',
      'picked_location': '已选择的位置',
      'required_field': '必填',
      'auto_calculated_from_km_and_round': '根据每圈公里数和圈数自动计算',
      'selected_image_too_large': '所选图片太大，请选择更小的图片。',
      'please_pick_location_on_map': '请在地图上选择地点',
      'please_select_date': '请选择日期',
      'please_select_time': '请选择时间',
      'save_failed': '保存失败：{error}',
      'publish_failed': '发布失败：{error}',
    },
  };

  static String text(String key, {Map<String, String> params = const {}}) {
    final code = UserLocaleController.languageCode.value;
    final template = _spotFormExtraValues[code]?[key] ??
        _extraValues[code]?[key] ??
        _values[code]?[key] ??
        _spotFormExtraValues[UserLocaleController.fallbackLanguageCode]?[key] ??
        _extraValues[UserLocaleController.fallbackLanguageCode]?[key] ??
        _values[UserLocaleController.fallbackLanguageCode]?[key] ??
        key;
    final mergedParams = <String, String>{
      'spot_term': spotTerm,
      'big_event_term': bigEventTerm,
      'spot_termLower': spotTerm,
      ...params,
    };
    var output = template;
    for (final entry in mergedParams.entries) {
      output = output.replaceAll('{${entry.key}}', entry.value);
    }
    return output;
  }

  static String languageLabel(String code) {
    switch (code) {
      case 'th':
        return 'ไทย';
      case 'zh':
        return '中文';
      default:
        return 'English';
    }
  }
}
